import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: '#20493C', // Fondo uniforme
          margin: '0',
          fontFamily: 'Arial, sans-serif',
        }}
      >
        <header
          style={{
            position: 'absolute',
            top: '0',
            width: '100%',
            display: 'flex',
            justifyContent: 'space-between',
            padding: '20px',
            backgroundColor: '#20493C',
            zIndex: 1000, // Asegura que el menú quede encima del contenido
          }}
        >
          
          <Link href="/" style={{ textDecoration: 'none', color: 'white', fontSize: '24px',
              fontWeight: 'bold',
              cursor: 'pointer', }}>
              <div>Terratrade</div>
            </Link>
          <nav
            style={{
              display: 'flex',
              gap: '70px',
              color: 'white',
              cursor: 'pointer',
              justifyContent: 'center',
              flex: 1,
            }}
          >
            <Link href="/" style={{ textDecoration: 'none', color: 'white' }}>
              <span>Home</span>
            </Link>
            <Link
              href="/acercaDeNosotros"
              style={{ textDecoration: 'none', color: 'white' }}
            >
              <span>Acerca de nosotros</span>
            </Link>
            <Link
              href="/perfil"
              style={{ textDecoration: 'none', color: 'white' }}
            >
              <span>Perfil</span>
            </Link>
            <Link
              href="/preguntasFrecuentes"
              style={{ textDecoration: 'none', color: 'white' }}
            >
              <span>Preguntas frecuentes</span>
            </Link>
            <Link
              href="/paginaPrincipal"
              style={{ textDecoration: 'none', color: 'white' }}
            >
              <span>Terrenos</span>
            </Link>
          </nav>
          <Link href="/login" style={{ cursor: 'pointer' }}>
            <Image
              src="/imagenes/personita.png"
              alt="personita inicio de sesion"
              width={80}
              height={80}
            />
          </Link>
        </header>

        {/* Contenido principal */}
        <main style={{ paddingTop: '10px', minHeight: '100vh' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
