import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{String(metadata.title ?? 'Default Title')}</title>
        <meta name="description" content={String(metadata.description ?? 'Default description')} />
      </head>
      <body style={{ backgroundColor: '#20493C', margin: 0, padding: 0 }}>
        <div className="navbar" style={{ position: 'absolute', top: '0', width: '100%', display: 'flex', justifyContent: 'space-between', padding: '20px', backgroundColor: '#20493C' }}>
          <div style={{ color: 'white', fontSize: '24px', fontWeight: 'bold', cursor: 'pointer' }}>
            TerraTrade
          </div>

          <div style={{ display: 'flex', gap: '70px', color: 'white', cursor: 'pointer', justifyContent: 'center', flex: 1 }}>
            <Link href="/" style={{ textDecoration: 'none', color: 'white' }}>
              <span>Home</span>
            </Link>
            <Link href="/acercaDeNosotros" style={{ textDecoration: 'none', color: 'white' }}>
              <span>Acerca de nosotros</span>
            </Link>
            <Link href="/perfil" style={{ textDecoration: 'none', color: 'white' }}>
              <span>Perfil</span>
            </Link>
            <Link href="/preguntasFrecuentes" style={{ textDecoration: 'none', color: 'white' }}>
              <span>Preguntas frecuentes</span>
            </Link>
            <Link href="/paginaPrincipal" style={{ textDecoration: 'none', color: 'white' }}>
              <span>Terrenos</span>
            </Link>
          </div>
          <div style={{ cursor: 'pointer' }}>
            <Image
              src="/imagenes/personita.png"
              alt="personita inicio de sesion"
              width={80}
              height={80}
            />
          </div>
        </div>
        <div style={{  minHeight: '100vh', color: 'white' }}>
          {children}
        </div>
      </body>
    </html>
  );
}
